apiVersion: v1
kind: Service
metadata:
  name: trustflow-web
  namespace: trustflow
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: trustflow-web
  ports:
    - name: http
      port: 80
      targetPort: 8080
